### PR TITLE
Add support for existing rooms

### PR DESCRIPTION
**Pull request by mittler-works**
Users can now let bots join to existing rooms. This may be useful for some test.

Also, updated a dependency.

### CODE REVIEW

**Comment by pedrobmarin** [comment]
Hi @mittler-works , thanks for your contribution.

I'm wondering if we need the extra room id to achieve this. Wouldn't this be possible if we only had the passwords as environment variables?

**Comment by mittler-works** [comment]
Well, yes :smile:
I thought, the naming could be confusing and that's a better way to tell apart. But sure, actually the `BIGBLUEBOT_ROOM_ID` variable is the same as `BIGBLUEBOT_ROOM`.
If it's documented in the readme it shouldn't be a problem to use the `BIGBLUEBOT_ROOM` for both. I'll edit the PR and commit an update.

**Comment by mittler-works** [comment]
By the way, thank you very much for the great tool!

**Comment by pedrobmarin** [comment]
> I thought, the naming could be confusing and that's a better way to tell apart.

Yeah. I kind of agree on this.

> By the way, thank you very much for the great tool!

No problem. Glad it's being useful for someone else. Your work here made me think what else we could turn automatic in cases like this. Maybe I'll submit some changes later on and ask for your opinion, if that's ok.

**Comment by mittler-works** [comment]
>Your work here made me think what else we could turn automatic in cases like this. Maybe I'll submit some changes later on and ask for your opinion, if that's ok.

Ye of course, I'm glad to contribute :)

**Pull request merged**
